spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.21:3306/spring-demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    username: yioks_admin
    password: yioks_admin